### ISSUE TITLE
Same photo in random slideshow

### ISSUE THREAD

**Issue by data-dude92** [NautiluX/slide#10]
Hello,

First of all, thanks for this extremely nice piece of software. Ive got a very nice digital photoframe thanks to you!

I do have one thing though: the slideshow selects photos at random. This however leads to the same photo often being shown within a few minutes (because it is truly random).

Is it maybe possible to not select a photo every time, but rather make a random list of the photos in the directory and then follow that order (when the list is done, create a new random list etc).

Many thanks,
DD

**Comment by NautiluX** [comment]
Hi @data-dude92 ,
thanks for opening this ticket. The current random selection has two advantages:
- newly added pictures can be selected with the next swap
- it's simple

That being said, I think implementing a shuffle selection instead of random should be possible, but we should make sure the first point doesn't get lost, i.e. reshuffle if a new image is added.

**Comment by data-dude92** [comment]
Good points and thanks for your quick answer. I will see if I can make a pull request as soon as I have some time.

How do you propose we make sure newly added pictures can be selected with the next swap? Because I was thinking of just shuffling the images array with the filenames and then looping through them all. When this is done, create a new shuffle. New images would be added when every image has been shown, this  can be a problem if you have a lot of images I guess?

**Comment by NautiluX** [comment]
Glad to see you want to contribute this!
I'm fine to start with that behavior, maybe we can just add a flag, so it's opt-in behavior?
say:
```
slide path/to/images
```
for random mode, and
```
slide path/to/images -s
```
for shuffle mode?

**Comment by NautiluX** [comment]
Hi @data-dude92,

I did a bit of refactoring to make adding the shuffle mode possible in a cleaner way. The implementation of the shuffle itself is still yours, so I added you as co-author.
See my PR: https://github.com/NautiluX/slide/pull/12
I'll leave the PR open so you can have a look at the changes I did and compare it to your implementation and try out if it works. I will merge it and create a release within the next days, if you have no concerns.

Kind regards,
Manuel

**Comment by NautiluX** [comment]
PR #12 merged, shuffle mode included in v0.9.4.
