### ISSUE TITLE
Stopping slideshow

### ISSUE THREAD

**Issue by brcent** [NautiluX/slide#13]
How do you stop the slideshow after you start it? it seems to take over the screen and even pressing the windows key may bring up the menu but it wont let me open anything. I am a noobie sorry if this is a stupid question.

**Comment by NautiluX** [comment]
You can stop it by pressing the escape key.

Ben center <notifications@github.com> schrieb am Mi., 26. Feb. 2020, 01:33:

**Comment by brcent** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by NautiluX** [comment]
Out of curiosity: Did you have to compile it on the pi zero or did it work with the release binaries? Cause they are built on a Pi 3

**Comment by brcent** [comment]
I just the regular install from your webpage and it seemed to work fine but I couldn’t stop it no matter what I did. I had to power off the pi to stop it. I am using  the pizero w. I setup dropbox to update a folder and I had your slide program showing pics from the folder. It was doing the blurs on the side and everything. I am trying to make something for my mom and dad to be able to see my pictures while I travel. I can send my pics to the dropbox folder and it will sync to the pizero using crontab. Then all they have to do is turn the tv to that input to see the new pictures. My problem is that if I autostart your program I won’t be able to get to the desktop to map the pi to their wifi. I am currently looking at going with GLslideshow in the xscreensaver. I had an issue that after I changed the photos the screensaver was still looking for the old pics and giving errors but I think I found a way to refresh the folder now so it may work. But it doesn’t look as good as your slideshow. Sent from Mail for Windows 10 From: Manuel DewaldSent: Wednesday, February 26, 2020 10:59 AMTo: NautiluX/slideCc: Ben center; AuthorSubject: Re: [NautiluX/slide] Stopping slideshow (#13) Out of curiosity: Did you have to compile it on the pi zero or did it work with the release binaries? Cause they are built on a Pi 3—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NautiluX** [comment]
the xscreensaver hack actually was the reason I started building this project ;) glad you also like it. :) I think you should be able to configure wifi headless with wpa_supplicant.conf, see https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md

**Comment by NautiluX** [comment]
Please respond in the Github UI, your mails are hard to read here lol

**Comment by brcent** [comment]
Sorry about that I was unaware it looked like that. I will check out the link. Thanks for responding.

**Comment by brcent** [comment]
I would still have issues if I cant get to the terminal.

**Comment by NautiluX** [comment]
You could access it via ssh I think

**Comment by NautiluX** [comment]
But it should be possible to stop it with esc. Guess that's an issue with your remote access client.
