### ISSUE TITLE
Image not scaling properly to display

### ISSUE THREAD

**Issue by HotWinterDays** [NautiluX/slide#14]
Hello, great little program but I am having an issue using it with hyperpixel4 GPIO display. It does not scale properly, it pads the image from the top and for some reason only shows about a quarter of the image even when I resize the image to be the same size as the display.

Is there a way to adjust how images are scaled? Or to define some sort of resolution? I am not very experienced in this, I am relatively tech savvy but not super familiar with programming or interpreting software code.

**Comment by HotWinterDays** [comment]
I figured it out.

**Comment by omegahack0** [comment]
What was the solution to the problem?
