### ISSUE TITLE
Applicaiton not fullscreen

### ISSUE THREAD

**Issue by omegahack0** [NautiluX/slide#17]
When having the application in a script that auto runs by being placed within the profile.d directory the application looks like it runs in a windowed mode taking up most of the screen, but not all of it. Oddly enough when I run the script separately it runs perfectly in full screen. This makes me think it might be something wrong with my method of automatically running the script. Thanks for any input or suggestions

**Comment by omegahack0** [comment]
the command that I am running is:
DISPLAY=:0.0 slide -t 120  -p /home/pi/Pictures 
Also I am running the most recent release

**Comment by NautiluX** [comment]
Here is a blogbost explaining how I set it up: https://opensource.com/article/19/2/wifi-picture-frame-raspberry-pi

**Comment by omegahack0** [comment]
for whatever reason I dont have the lxsession directory, and if I make it then for whatever reason I got other issues like having simply a blank screen with only the cursor, that is why I put the script ion the profile.d directory.

**Comment by NautiluX** [comment]
Interesting. Which Raspberry Pi version are you using? Which OS?

**Comment by omegahack0** [comment]
Honestly I am not sure which OS I am using, but I am using a Raspberry Pi W. How would I check the OS?

**Comment by omegahack0** [comment]
On another note I tried creating the Directory lxsession/LXDE/ since it didnt exist and my desktop was just black with only my cursor visible.

**Comment by NautiluX** [comment]
you're using a Rapsberry Pi zero W?
you can run `cat /etc/issue` to figure out which OS it is.

**Comment by omegahack0** [comment]
Yea im using a raspberry Pi zero W and the output from cat says Raspbian GNU/Linux 10
