### ISSUE TITLE
Could it work with animated GIF or PNG?

### ISSUE THREAD

**Issue by DFF-fred** [NautiluX/slide#18]
Hi!
Great app, simple set up. Thank you for this. Now I've tried so I know it doesn't work, but could it easily be modified to accept animated GIFs or PNGs, eventually mp4? Really not familiar with C++ but could make an effort ;-)

Thank you.

**Comment by NautiluX** [comment]
Hi @DFF-fred, I think PNG shouldn't be a big issue, guess is we just need to allow it in the filter [here|https://github.com/NautiluX/slide/blob/7b77e62af5e07cdb612134ac5024100887a8033f/src/pathtraverser.cpp#L25] and [here|https://github.com/NautiluX/slide/blob/7b77e62af5e07cdb612134ac5024100887a8033f/src/pathtraverser.cpp#L49].
GIFs and MP4s will be a bigger effort.

**Comment by DFF-fred** [comment]
Hey! That was a very fast response! 

So I was actually updating the code and did find the file mentioned above. In fact both GIF and PNG files open, but they are not displaying the animation. :-( 
I suppose there must be another library to do that (and thank you for your message: I was getting crazy as it worked for GIF but not for PNG, always opening the GIF files -> I was just forgetting to edit the second section).

The blur effect is really not bad on transparent PNG also :-)

I think mp4 can wait but I'd be happy to get the animation part of those GIF and PNG files. Will continue searching, if you have any idea please do not hesitate.
Thank you.

**Comment by NautiluX** [comment]
so animations are indeed more complicated and tbh I don't see them in the scope for this project, yet. However, if you feel like you want to contribute that, I'd be happy to review or assist.
