### ISSUE TITLE
Could not connect to display

### ISSUE THREAD

**Issue by Steeps5** [NautiluX/slide#19]
I'm running this on a Raspberry Pi Zero W and I installed the required dependencies. I have one .jpg image in the share folder.

I run: `slide -t -o -b -p /home/pi/share` and I get `qt.qpa.screen: QXcbConnection: Could not connect to display` as the result.

Same result with just `slide -p /home/pi/share`.

Any help?

**Comment by Steeps5** [comment]
I have a feeling this was because I was using Raspberry OS Lite with no GUI.

**Comment by NautiluX** [comment]
Glad you got it working! Can you quickly share how? What os are you using
now? There's another pi zero issue open - this info might help others :).

Steeps5 <notifications@github.com> schrieb am Mo., 13. Juli 2020, 05:37:
