### ISSUE TITLE
Starting from SSH-connection: qt.qpa.screen: QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by smathev** [NautiluX/slide#20]
Hi.

I wanted to use a RPi as a picture frame, and have installed Slide following your guide to installation. Everything works when I locally (on the Pi, using screen and keyboard) start Slide.

But, I wanted to develop/start/restart/etc. remotely, so that I don't have a picture frame with a keyboard attached. This is where my issue arises:
When I try to start Slide remotely, via an SSH-connection I get the following error:
Command: slide -p Documents/
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

Is there any way to fix this, or should I have a keyboard ready to attach whenever I want to reset/restart Slide?

Thanks in advance.

**Comment by NautiluX** [comment]
I assume you have an X Server running. To start an application on that X Server, you need to set the `DISPLAY` variable when running the application from ssh (like slide in your case). To figure out the right value, easiest is to attach a keyboard to the Pi, open a terminal and do 
```
echo $DISPLAY
```
then you should be able to run the slideshow via ssh by using
```
DISPLAY=<value-from-above> slide -p Documents/
```

**Comment by NautiluX** [comment]
assuming this is solved.
