### ISSUE TITLE
Artifactual image display

### ISSUE THREAD

**Issue by Oberloewe** [NautiluX/slide#26]
When I start the slideshow, the displayed JPG images appear in a very poor quality. There are artifacts (e.g. when images with roofs are displayed) and on closer inspection it seems that there is no antialiasing. 
When I view the JPG images in the desktop environment with the default viewer, the image also appears in poor quality, but only for a very short time (about 1 second). After that, the images are displayed in the expected quality. I am using a Raspberry Pi 3B running Raspbian Buster with LXDE desktop environment. 

Since I' m new to the topic, unfortunately I don't know if my problem is due to a wrong setting of Slide or if it's a wrong setting of the OS.

**Comment by NautiluX** [comment]
Can you probably provide an example source image along screenshots with slide and the system preview software so I can try to reproduce the issue?

**Comment by Oberloewe** [comment]
Hi. Here are two photos of the same picture (I took them with my smartphone). You can see the displayed artifacts best on the houses rooftops. I use a PI 3 with the latest Respberry OS (Desktop) and the images are located on a USB flash drive. The display is a HD ready TV with 720p. If I use FEH to watch the images the artifactical effect can also be seen but approx. just for 1-2 seconds. It seems like the picture is displayed in a low quality first and after doing some post calculations the quality is rised. But if I use SLIDE the images are displayed in the low quality and reside in this low quality.


![IMG_20210124_203328](https://user-images.githubusercontent.com/76879693/105641645-6e5a3900-5e85-11eb-9e31-d0c80e133e66.jpg)
![IMG_20210124_202146](https://user-images.githubusercontent.com/76879693/105641648-75814700-5e85-11eb-8e35-486ceef89ced.jpg)

**Comment by NautiluX** [comment]
what's the image size of the original picture?

**Comment by Oberloewe** [comment]
I attached the original image, but the size does not really matter. I already tried a comprimised version of the image as well as other images. 
Unfortunately I have never built such a project from the sources...


![Luftbild](https://user-images.githubusercontent.com/76879693/109693637-316f1980-7b8a-11eb-99ed-0902422e9e33.jpg)

**Comment by NautiluX** [comment]
I'll try to add it as option, so you can try it out. Guess it'll use more resources to do the smooth scaling.

**Comment by NautiluX** [comment]
Please try release [0.9.7](https://github.com/NautiluX/slide/releases/tag/v0.9.7). I changed scaling to smooth by default, since it performs well on Raspberry Pi 3 as well as the Raspberry Pi zero.

**Comment by Oberloewe** [comment]
I tried the latest 0.9.8 release and its working perfectly now. 
Many thanks for your efforts.
