### ISSUE TITLE
Plans to support png and other file extensions?

### ISSUE THREAD

**Issue by 62274677** [NautiluX/slide#27]
I am trying to use this as a live photo frame using a folder synced with google photos, but not all of the images are jpg. Some are png or HEIF/HEIC. Any plans to cover those kinds of file types (or guidance of where to make edits to allow for this)? Even just png would be nice.

**Comment by NautiluX** [comment]
I think supporting PNG should be as easy as allowing the file extension [here](https://github.com/NautiluX/slide/blob/7338aee6ba20a83d22ebc2f604794cd716672412/src/pathtraverser.cpp#L25) and [here](https://github.com/NautiluX/slide/blob/7338aee6ba20a83d22ebc2f604794cd716672412/src/pathtraverser.cpp#L49) I don't have any heif or heic example files, but based on some short research it seems they are not by default supported by QT QPixmaps. It's probably possible using [this](https://github.com/jakar/qt-heif-image-plugin) third party plugin

**Comment by NautiluX** [comment]
PNG is supported with version 0.9.8. I will close this issue since supporting HEIF/HEIC seems not to be easily achievable. You may want to convert your images to PNG before giving them to slide (imagemagick seems to be capable of doing that).
