### ISSUE TITLE
Pictures are shown cropped

### ISSUE THREAD

**Issue by magica237** [NautiluX/slide#29]
Hello, I love your program and I am using it at home and now preparing the picture frame for my parents.
First after installation of version 0.9.0 (from the article in opensource.com) on Raspi 3B+ I've had a problem: the pictures were changing size, constantly adjusting. After update to version 0.9.5 it is just subtle, but the pictures are showed cropped. After several pictures shown, this problem disapears. Problem disappears sooner when the portrait oriented pictures are shown.
For the testing purpose I have used 8 pictures.   All of them have red frame, so you can clearly see when whole picture is visible.
Maybe when the first picture where the background blur or zoom is really applied is shown, just then are all pictures scaled correctly?
The video of my test slideshow is [here](https://nubo.punkto.info/s/LzJHcrYbSMBdknS)

**Comment by NautiluX** [comment]
I had similar issues with early versions of slide as well, but I thought it was fixed with one of the latest releases. Would you mind attaching those pictures so I can try to investigate? Also, what's your screen's resolution? My gut feeling is qt doesn't know how big the screen is.

**Comment by NautiluX** [comment]
@pepe82sh is this the issue you try to solve with the 1x1px window size?

**Comment by pepe82sh** [comment]
It's the exact problem I did solve using the 1x1px window size. Actually, I was attempting to do the same thing: A picture frame for my parents. I used a 800x480 touch screen, and the problem disappeared as soon as the window size was smaller than the screen size. I figured that 1x1 will always be smaller than any screen :) If I'm right you should be able to reproduce the behavior by either using a smaller screen, or change the window size to anything bigger than your current screen.

**Comment by NautiluX** [comment]
Would you mind carving that part out of your pr so I can merge it? Or would
you want to see the tofu part merged as well?

pepe <notifications@github.com> schrieb am Di., 2. März 2021, 19:10:

**Comment by magica237** [comment]
Test pictures are stored here: https://nubo.punkto.info/s/jfYkSMp5ArRZ35C
I have the screeen with resolution 1024x600.
Resolution I have set in /boot/config.txt  by adding a line: 
hdmi_cvt=1024 600 60 3 0 0 1

I hope it helps.

**Comment by NautiluX** [comment]
PR merged, will create a new release as soon as I get to it.

**Comment by pepe82sh** [comment]
> Would you mind carving that part out of your pr so I can merge it? Or would you want to see the tofu part merged as well? pepe <notifications@github.com> schrieb am Di., 2. März 2021, 19:10:
> […](#)

I have created pull request #30 with just the one change. The other feature would need testing with a non touch screen to be safely merged, so I don't insist.

**Comment by NautiluX** [comment]
@magica237 can you check if release [https://github.com/NautiluX/slide/releases/tag/v0.9.6](0.9.6) fixes your issue?

**Comment by magica237** [comment]
@NautiluX I have tested the version 0.9.6 on two devices, both are working perfectly. Thank you for fixing the issue!

**Comment by NautiluX** [comment]
Great to hear!
