### ISSUE TITLE
Add support for per-folder display options

### ISSUE THREAD

**Issue by alfred-reynolds** [NautiluX/slide#38]
I've got 2 folders containing images I want to display. One I want to fit to the screen and have the blurred background (the current behavior) and one I want to stretch/crop to the frame (use the new --stretch option). I want to mix both these images for display on my from (one is family pictures which I want to fit, one is landscapes which I want to stretch).
I've got code implementing this in https://github.com/alfred-reynolds/slide/tree/folder_options , I can turn it into a PR once my other PR is committed :)

**Comment by NautiluX** [comment]
Interesting idea, feel free to open a PR. I took a look at that code, and have a few remarks:
* Let's not use the option object to transport processing results (image aspect)
* Let's initialize the option object with the settings from the command line (i.e. stretch) and pass that as copy into the functions. Then override options where a config file is present with the options defined in the file. Currently it's created each time within the functions that use it with the with the option that we already have as argument to the function (+information/processing results about the image).

**Comment by alfred-reynolds** [comment]
Will do!

**Comment by alfred-reynolds** [comment]
Pull request sent: #41
