### ISSUE TITLE
shuffle picture displays instead of random

### ISSUE THREAD

**Issue by Elbab2021** [NautiluX/slide#39]
Hi,
I'm new to github...and I installed slide in a Raspi 3.
The slider works fine.
The pictures are displayed in a random order.
Is there a posibility to display the picturen in a sequential order and the from beinning again (shuffle)
.
In the description is a switch called [-s] that should be placed after teh pictures folder.
But it fails.. Is doesn't matter where in which order I set the [-s]  the slider doesn'work then.

Thanks for advice..
rgds. juan

**Comment by NautiluX** [comment]
Hi @Elbab2021, yes it sounds like the shuffle mode should do what you want. Can you share the exact command you're trying?

**Comment by Elbab2021** [comment]
Hi
cmd line ist inserted into the boot startup function of my Raspi..

`**@slide -t 10 -o 200 -p /home/pi/cloud/Diashow**    // working with random pictures selection`
with this parameters the slide works fine, but the pictures are taken randomly from the path.
In the slide description is mentioned that the shuffle parameter [s] should be after the path.. like the [r] parameter


`**@slide -t 10 -o 200 -p /home/pi/cloud/Diashow -s**    // not working `
if I set them there the slide doesn't start up.
I tried the shuffle parameter in different positions of the cmd line, with no success..

...any idea?

Slide installation done under user : sudo su
with this cmd's:
wget https://github.com/NautiluX/slide/releases/download/v0.9.0/slide_pi_stretch_0.9.0.tar.gz
tar xf slide_pi_stretch_0.9.0.tar.gz
mv slide_0.9.0/slide /usr/local/bin/

User after boot: pi


- raspi OS - Buster from may 05, 2021with all updates.
- slide version 0.9.0

thx... Juan

**Comment by NautiluX** [comment]
Shuffle support was added in 0.9.4, please use the [latest release](https://github.com/NautiluX/slide/releases/tag/v0.9.13) and try again.
