### ISSUE TITLE
Support for recursive folders

### ISSUE THREAD

**Issue by GuGuss** [NautiluX/slide#4]
Hi,

I love this script and the simplicity to set it up.

I'd love if the script could support multiple folders. I could probably open a pull request if I find the time to dive in the code base :)

**Comment by NautiluX** [comment]
Thanks! Sure, that shouldn't be too hard.

I see two different things in your issue.

1. Use all images in a given folder and subfolders recursively
This should be added [here](https://github.com/NautiluX/slide/blob/ab83982cdd847e8ed4c2e1940620f8b719b0ebd5/src/imageselector.cpp#L23) and could even be the default, I think.
2. Support passing multiple folders. This needs to be added to the [getopt loop](https://github.com/NautiluX/slide/blob/ab83982cdd847e8ed4c2e1940620f8b719b0ebd5/src/main.cpp#L25) and will change a few more things (path needs to be an array ... ).

Both are valid feature requests I think, which one are you hunting for?

**Comment by NautiluX** [comment]
Regarding 1: This commit will add a recursive mode (-r flag): https://github.com/NautiluX/slide/commit/09fc431034a9b0c3f7ce488a7a5d4fd34593afbf
However, I did not yet create a release out of it. You can nevertheless try it out by building it yourself (see https://github.com/NautiluX/slide#build).

**Comment by NautiluX** [comment]
Recursive folder support included in latest release with -r flag: https://github.com/NautiluX/slide/releases/tag/v0.9.2
