### ISSUE TITLE
shuffle vs sorted in the config.json

### ISSUE THREAD

**Issue by mikey4321** [NautiluX/slide#47]
Suspect its just a typo in the instructions, but both shuffle and sorted options state that they enable the shuffle mode in the instructions.

`shuffle : set to true to enable shuffle mode for file display`
`recursive : set to true to enable recursive mode for file display`
`sorted : set to true to enable **_shuffle_** mode for file display`

**Comment by alfred-reynolds** [comment]
That would be my bug, thanks for noticing it! I'll fix it and make a PR.
