### ISSUE TITLE
Problem with the size of the photos

### ISSUE THREAD

**Issue by marjimmjn** [NautiluX/slide#5]
Hello, first of all, thanks for your scrip, it has helped me a lot.
I have a problem, when the slide starts, the photos change size by themselves, from small to large. After a few minutes the photos no longer change size, they look good. Why is this happening? Thank you.

**Comment by marjimmjn** [comment]
Ok I see the same problem in other issue. Write in other issue.

**Comment by NautiluX** [comment]
Let's use this issue to track that bug. I irregularly see the same. The [other issue](https://github.com/NautiluX/slide/issues/1) is originally about a different problem. Do you consistently experience the issue or only some-times? I see it only from time to time.

**Comment by marjimmjn** [comment]
Perfect, we continue for this issue, not to mix.
When the pi starts, the slide is launched, and it starts to perform the zoom error. At 2 or 3 min, stop making the zoom error. Whenever I turn it off and on it happens.
Thanks !!!

**Comment by NautiluX** [comment]
This is what the issue looks like:
> ![pi-slide-bug](https://user-images.githubusercontent.com/22662175/66858191-c1d99980-ef56-11e9-9580-8a884246b266.gif)

**Comment by marjimmjn** [comment]
Yes exactly the same. How could i fix it?

**Comment by NautiluX** [comment]
I added a workaround which fixes the issue for me so far, although it makes the startup of the application a bit uglier. can you have a look at [v0.9.1](https://github.com/NautiluX/slide/releases/tag/v0.9.1) ?

**Comment by NautiluX** [comment]
Assume this is solved as I didn't hear back from @marjimmjn . Feel free to reopen if the issue persists.

**Comment by thenakedthunder** [comment]
Hi, I have the very same problem with the zoom, pics bounce the same way on my pi. Is there a chance to get my hands on that v0.9.1?
