### ISSUE TITLE
qt5-daufault not available any more

### ISSUE THREAD

**Issue by smilebasti** [NautiluX/slide#56]
Hi, i just tried following your guide: [https://opensource.com/article/19/2/wifi-picture-frame-raspberry-pi](https://opensource.com/article/19/2/wifi-picture-frame-raspberry-pi).

My error is during: `sudo apt install libexif12 qt5-default`. I get:  `package qt5-default is not available`.

Any ideas how to solve that? Is qt6 compatible?

Thanks ahead :)

**Comment by paulchen** [comment]
Just in case someone else stumbles upon this problem: `slide` runs on a recent Raspberry Pi OS (bullseye) without problems. Only the packages you need to install are different.

I installed:
- `qtbase5-dev`
- `libexif-dev`
