### ISSUE TITLE
Floating point exception with subdirs

### ISSUE THREAD

**Issue by jaal2001** [NautiluX/slide#6]
Hi,

when I'm using a directory, which does contain subdirs and these do include spaces in the names (like "Albums from 2019"), the app does crash with "Floating point exception".

When I start slide directly with the spaces dir, it does work fine.

Happens at least on Raspbian GNU/Linux 10 on my Raspberry PI B.

Regards
JJ

**Comment by NautiluX** [comment]
Hi @jaal2001, thanks for submitting this issue! I will have a look as soon as I get to it.
In case you're trying this: use of images in recursive folders is not yet supported, see issue #4 .

**Comment by jaal2001** [comment]
Well, than I assume that would be the main root cause of my issue :-)

**Comment by NautiluX** [comment]
Hi @jaal2001, I tried to reproduce your issue, but I couldn't. Are you using the latest version of slide?

**Comment by NautiluX** [comment]
Hi @jaal2001, this commit should fix it and add a recursive mode (-r flag):
https://github.com/NautiluX/slide/commit/09fc431034a9b0c3f7ce488a7a5d4fd34593afbf
However, I did not yet create a release out of it. You can nevertheless try it out by building it yourself ( see https://github.com/NautiluX/slide#build).

**Comment by NautiluX** [comment]
https://github.com/NautiluX/slide/releases/tag/v0.9.2

**Comment by tsando** [comment]
Hey, thanks for this solution. Just a question, was this ever merged to master or in any of the releases in the end or not yet?

**Comment by NautiluX** [comment]
Yes it should be in

Tanya Sandoval <notifications@github.com> schrieb am Do., 28. Mai 2020,
17:05:
