### ISSUE TITLE
Text Overlays

### ISSUE THREAD

**Issue by vbtrek** [NautiluX/slide#7]
This is a great slideshow app, thanks. Just a suggestion, would it be possible to overlay some text on the image? I'd like to see the Date Taken and the folder name the photo has come from.

I also get some photos that a very pixelated, is there a log I can view to see if I can find if there is any particular reason for this?

Running on a raspberry Pi running the latest raspbian.

Thanks

**Comment by NautiluX** [comment]
Hi, text overlays sound like a nice feature, but it is not yet planned. If I find time for specific toggles, I will implement them, but would also welcome PRs. :-)

Regarding your issue with the "pixelated" image, can you provide a screenshot of it and maybe attach the original image that produces the issue?

**Comment by Bond198** [comment]
+1 for a text overlay. I've been experimenting with exifgrep and exifprobe. No luck so far.

**Comment by NautiluX** [comment]
Release [0.9.9](https://github.com/NautiluX/slide/releases/tag/v0.9.9) adds support for text overlays. The problem with the poor scaling should be fixed there as well.
