### ISSUE TITLE
Passing recursive folder with spaces

### ISSUE THREAD

**Issue by jerzynowakowski** [NautiluX/slide#8]
First of all - thank you for this amazing software!

How can I pass a folder with spaces? Tried everything like
`slide -t 10 -o 200 -p /mnt/folder\ name/ -r`
`slide -t 10 -o 200 -p "/mnt/folder name/" -r`
`slide -t 10 -o 200 -p /mnt/folder name/ -r`
`slide -t 10 -o 200 -p '/mnt/folder name/' -r`

but nothing works. Please advise if possible. Thanks!

**Comment by NautiluX** [comment]
Should be fixed in [latest release](https://github.com/NautiluX/slide/releases/tag/v0.9.3), please re-test.
